apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployemnt
spec:
  replicas: 1
  selector:
    matchLabels:
      name: db-app-pod
      app: guestbook-app
  template:
    metadata:
      name: db-app-pod
      labels:
        name: db-app-pod
        app: guestbook-app
    spec:
      containers:
        - name: db
          image: redis
          ports:
            - containerPort: 6379
