apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  selector:
      app: redis
      role: master
  ports:
  - port: 6379
    targetPort: 6379
