apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  replicas: 1
  selector:
    app: redis
    role: master
  template:
    metadata:
      name: redis
      labels:
        app: redis
        role: master
    spec:
      containers:
        - name: redis-master
          image: redis:2.8.23
          ports:
            - containerPort: 6379
