apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      name: redis
      labels:
        app: redis
        role: master
    spec:
      containers:
        - name: redis-master
          image: redis
          ports:
            - containerPort: 6379
