apiVersion: v1
kind: Service
metadata:
  name: db-app-service
  labels:
      name: db-app-service
      app: guestbook-app
spec:
  selector:
      name: db-app-pod
      app: guestbook-app
  ports:
  - port: 6379
    targetPort: 6379
