apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  labels:
      name: web-app-service
      app: guestbook-app
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
  selector:
      name: web-app-pod
      app: guestbook-app
  
