apiVersion: v1
kind: Service
metadata:
  name: guestbook
  labels:
      app: guestbook
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: http-server
      nodePort: 32000
  selector:
      app: guestbook
  
