apiVersion: v1
kind: Service
metadata:
  name: guestbook
  labels:
      app: guestbook
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: http-server
  selector:
      app: guestbook
  
